services:

  mariadb:
    image: mariadb:11
    container_name: cesizen-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: cesizen
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./cesizen-back
      dockerfile: Dockerfile
    container_name: cesizen-back
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build:
      context: ./cesizen-front
      dockerfile: Dockerfile
    container_name: cesizen-front
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - appnet

networks:
  appnet:

volumes:
  mariadb_data: