export interface DiagnosticEventMock {
  eventId: string;
  label: string;
  lcu: number;
}

export const DIAGNOSTIC_EVENTS_MOCK: DiagnosticEventMock[] = [
  { eventId: '1', label: 'Décès du conjoint', lcu: 100 },
  { eventId: '2', label: 'Divorce', lcu: 73 },
  { eventId: '3', label: 'Séparation conjugale', lcu: 65 },
  { eventId: '4', label: 'Emprisonnement', lcu: 63 },
  { eventId: '5', label: 'Décès d’un membre proche de la famille', lcu: 63 },
  { eventId: '6', label: 'Blessure ou maladie personnelle', lcu: 53 },
  { eventId: '7', label: 'Mariage', lcu: 50 },
  { eventId: '8', label: 'Perte d’emploi', lcu: 47 },
  { eventId: '9', label: 'Réconciliation conjugale', lcu: 45 },
  { eventId: '10', label: 'Retraite', lcu: 45 },
  { eventId: '11', label: 'Changement de santé d’un membre de la famille', lcu: 44 },
  { eventId: '12', label: 'Grossesse', lcu: 40 },
  { eventId: '13', label: 'Difficultés sexuelles', lcu: 39 },
  { eventId: '14', label: 'Arrivée d’un nouveau membre dans la famille', lcu: 39 },
  { eventId: '15', label: 'Réajustement professionnel', lcu: 39 },
  { eventId: '16', label: 'Changement de situation financière', lcu: 38 },
  { eventId: '17', label: 'Décès d’un ami proche', lcu: 37 },
  { eventId: '18', label: 'Changement de responsabilités professionnelles', lcu: 29 },
  { eventId: '19', label: 'Départ d’un enfant du foyer', lcu: 29 },
  { eventId: '20', label: 'Problèmes avec la belle-famille', lcu: 29 },
  { eventId: '21', label: 'Réussite personnelle remarquable', lcu: 28 },
  { eventId: '22', label: 'Début ou fin d’un travail du conjoint', lcu: 26 },
  { eventId: '23', label: 'Début ou fin d’études', lcu: 26 },
  { eventId: '24', label: 'Changement de conditions de vie', lcu: 25 },
  { eventId: '25', label: 'Révision des habitudes personnelles', lcu: 24 },
  { eventId: '26', label: 'Problèmes avec le patron', lcu: 23 },
  { eventId: '27', label: 'Changement d’horaires ou de conditions de travail', lcu: 20 },
  { eventId: '28', label: 'Changement de résidence', lcu: 20 },
  { eventId: '29', label: 'Changement d’école', lcu: 20 },
  { eventId: '30', label: 'Changement d’activités sociales', lcu: 18 },
  { eventId: '31', label: 'Changement d’habitudes de sommeil', lcu: 16 },
  { eventId: '32', label: 'Changement d’habitudes alimentaires', lcu: 15 },
  { eventId: '33', label: 'Vacances', lcu: 13 },
  { eventId: '34', label: 'Noël', lcu: 12 },
  { eventId: '35', label: 'Petites infractions à la loi', lcu: 11 },
  { eventId: '36', label: 'Mariage d’un enfant', lcu: 50 },
  { eventId: '37', label: 'Problèmes financiers majeurs', lcu: 38 },
  { eventId: '38', label: 'Changement majeur dans les loisirs', lcu: 19 },
  { eventId: '39', label: 'Changement majeur dans les activités religieuses', lcu: 19 },
  { eventId: '40', label: 'Changement majeur dans les habitudes sociales', lcu: 18 },
  { eventId: '41', label: 'Hypothèque importante', lcu: 31 },
  { eventId: '42', label: 'Hypothèque ou prêt inférieur à 10 000 €', lcu: 17 },
  { eventId: '43', label: 'Changement dans la fréquence des disputes conjugales', lcu: 35 }
];
