# ---------- STAGE 1 : BUILD ----------
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
# `npm ci` échoue si le lockfile est hors de sync dans l'image Docker.
# Utiliser `npm install` pour une construction plus robuste dans l'image.
RUN npm install

COPY . .
RUN npm run build

# ---------- STAGE 2 : NGINX ----------
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/cesizen-front/browser/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
