# =============================================================================
# DATASOURCE
# =============================================================================
spring.datasource.url=jdbc:mariadb://localhost:3310/cesizen
spring.datasource.username=cesizen_user
spring.datasource.password=un_mot_de_passe_fort
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =============================================================================
# SERVEUR
# =============================================================================
server.port=8081

# =============================================================================
# JPA
# =============================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================================================
# SPRINGDOC / SWAGGER
# =============================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# =============================================================================
# JWT
# =============================================================================
jwt.secret=ta_clé_base64_de_dev

# =============================================================================
# COOKIES
# =============================================================================
app.cookies.secure=false

# =============================================================================
# MAIL DEV
# =============================================================================
spring.mail.username=dev@cesizen.local
spring.mail.password=dev-password

# =============================================================================
# FRONTEND
# =============================================================================
app.frontend-url=http://localhost:4200
