spring.datasource.url=jdbc:mariadb://mariadb:3306/cesizen
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.port=8080

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
