# =============================================================================
# DATASOURCE
# =============================================================================
spring.datasource.username=cesizen_user
spring.datasource.password=un_mot_de_passe_fort

# =============================================================================
# JPA
# =============================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================================================
# SPRINGDOC / SWAGGER
# =============================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# =============================================================================
# JWT
# =============================================================================
jwt.secret=ta_clé_base64_de_dev