-- liquibase formatted sql
-- changeset damien:007_seed_diagnostic_events

INSERT INTO diagnosticEvent (eventID, eventLabel, eventLCU) VALUES
(UUID(), 'Décès du conjoint', 100),
(UUID(), 'Divorce', 73),
(UUID(), 'Séparation conjugale', 65),
(UUID(), 'Emprisonnement', 63),
(UUID(), 'Décès d’un membre proche de la famille', 63),
(UUID(), 'Blessure ou maladie personnelle', 53),
(UUID(), 'Mariage', 50),
(UUID(), 'Perte d’emploi', 47),
(UUID(), 'Réconciliation conjugale', 45),
(UUID(), 'Retraite', 45),
(UUID(), 'Changement de santé d’un membre de la famille', 44),
(UUID(), 'Grossesse', 40),
(UUID(), 'Difficultés sexuelles', 39),
(UUID(), 'Arrivée d’un nouveau membre dans la famille', 39),
(UUID(), 'Réajustement professionnel', 39),
(UUID(), 'Changement de situation financière', 38),
(UUID(), 'Décès d’un ami proche', 37),
(UUID(), 'Changement de responsabilités professionnelles', 29),
(UUID(), 'Départ d’un enfant du foyer', 29),
(UUID(), 'Problèmes avec la belle-famille', 29),
(UUID(), 'Réussite personnelle remarquable', 28),
(UUID(), 'Début ou fin d’un travail du conjoint', 26),
(UUID(), 'Début ou fin d’études', 26),
(UUID(), 'Changement de conditions de vie', 25),
(UUID(), 'Révision des habitudes personnelles', 24),
(UUID(), 'Problèmes avec le patron', 23),
(UUID(), 'Changement d’horaires ou de conditions de travail', 20),
(UUID(), 'Changement de résidence', 20),
(UUID(), 'Changement d’école', 20),
(UUID(), 'Changement d’activités sociales', 18),
(UUID(), 'Changement d’habitudes de sommeil', 16),
(UUID(), 'Changement d’habitudes alimentaires', 15),
(UUID(), 'Vacances', 13),
(UUID(), 'Noël', 12),
(UUID(), 'Petites infractions à la loi', 11),
(UUID(), 'Mariage d’un enfant', 50),
(UUID(), 'Problèmes financiers majeurs', 38),
(UUID(), 'Changement majeur dans les loisirs', 19),
(UUID(), 'Changement majeur dans les activités religieuses', 19),
(UUID(), 'Changement majeur dans les habitudes sociales', 18),
(UUID(), 'Hypothèque importante', 31),
(UUID(), 'Hypothèque ou prêt inférieur à 10 000 €', 17),
(UUID(), 'Changement dans la fréquence des disputes conjugales', 35);